import Head from 'next/head';
import Image from 'next/image';
import {ethers} from 'ethers';
import styles from "../styles/Home.module.css"
import { useState } from 'react';

export default function Home(){

  const [account, setAccount] = useState(null)
  const [walletAddress , setWalletAddress] = useState(null)

  const walletConnect = async () => {
      try {
       if (window.ethereum) {
        const accounts = await window.ethereum.request({method : "eth_requestAccounts"});
        if (accounts == null){
          sessionStorage.clear();
        }
        if (await accounts.length > 0){
          setAccount(accounts[0]);
          if(accounts != null){
            sessionStorage.setItem("Account Address" , `${accounts}`)
            setWalletAddress(sessionStorage.getItem("Account Address"));
          }
        } else {
          setAccount(accounts);
          sessionStorage.setItem("Account Address" , `${accounts}`)
        }
       }
      } catch (error){
        console.log(error);
      }
  }

  return(
    <div  className={styles.container}>
       <Head>
        <title>Buy Sudeep A Drink</title>
        <meta name="description" content='Generated by create next app'/>
        <link rel="icon" href="/favicon.ico" />
       </Head>
       <main className={styles.main}>
       <h1>Buy Sudeep A Drink and Enjoy with Your Buddies</h1>
       {walletAddress == null ? <button onClick={walletConnect}>wallet connect</button> : <button>connected</button> }
       </main>
       <footer>

       </footer>
    </div>
  )
}